// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziaiouideirqiwtfbayg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYWlvdWlkZWlycWl3dGZiYXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMzQ2MTksImV4cCI6MjA1NjcxMDYxOX0.ouib0E1uwChfWosTpADsk7Al9__HElnjPIcLblxYep8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);